import { LockOutlined, StopOutlined, UserAddOutlined } from '@ant-design/icons';
import { PageContainer, ProTable, type ProColumns } from '@ant-design/pro-components';
import { App, Button, Descriptions, Drawer, Form, Input, Modal, Space, Tag } from 'antd';
import { useIntl } from '@umijs/max';
import { useState } from 'react';
import { listAccounts, registerAccount, resetPassword, updateAccount, type PlayerAccount } from '@/services/players';

export default function Accounts() {
  const intl = useIntl(); const { message } = App.useApp(); const [drawer, setDrawer] = useState<PlayerAccount>(); const [passwordId, setPasswordId] = useState<number>(); const [registerOpen, setRegisterOpen] = useState(false); const [form] = Form.useForm(); const [registerForm] = Form.useForm();
  const t = (id: string, fallback: string) => intl.formatMessage({ id, defaultMessage: fallback });
  const columns: ProColumns<PlayerAccount>[] = [
    { title: t('players.account.id', '账号 ID'), dataIndex: 'account_id', search: false },
    { title: t('players.account.username', '用户名'), dataIndex: 'username', render: (_, row) => <a onClick={() => setDrawer(row)}>{row.username}</a> },
    { title: t('players.account.email', '邮箱'), dataIndex: 'email' },
    { title: t('players.account.group', '权限组'), dataIndex: 'group_id', search: false },
    { title: t('players.account.status', '状态'), dataIndex: 'state', valueEnum: { 0: { text: t('players.account.active', '正常'), status: 'Success' }, 1: { text: t('players.account.banned', '封禁'), status: 'Error' } }, render: (_, row) => <Tag color={row.state ? 'error' : 'success'}>{row.state ? t('players.account.banned', '封禁') : t('players.account.active', '正常')}</Tag> },
    { title: t('players.account.lastLogin', '最后登录'), dataIndex: 'lastlogin', search: false },
    { title: t('common.actions', '操作'), valueType: 'option', render: (_, row, __, action) => <Space><Button type="link" size="small" onClick={() => setDrawer(row)}>{t('common.detail', '详情')}</Button><Button type="link" size="small" icon={<LockOutlined />} onClick={() => { setPasswordId(row.account_id); form.resetFields(); }}>{t('players.account.resetPassword', '重置密码')}</Button><Button type="link" danger={row.state === 0} size="small" icon={<StopOutlined />} onClick={async () => { await updateAccount(row.account_id, { state: row.state ? 0 : 1 }); message.success(row.state ? t('players.account.unbanned', '已解禁') : t('players.account.bannedSuccess', '已封禁')); action?.reload(); }}>{row.state ? t('players.account.unban', '解禁') : t('players.account.ban', '封禁')}</Button></Space> },
  ];
  const labels: Record<string, string> = { account_id: t('players.account.id', '账号 ID'), username: t('players.account.username', '用户名'), email: t('players.account.email', '邮箱'), sex: t('players.account.sex', '性别'), group_id: t('players.account.group', '权限组'), state: t('players.account.status', '状态'), lastlogin: t('players.account.lastLogin', '最后登录'), last_ip: t('players.account.lastIp', '最后 IP') };
  return <PageContainer title={t('players.accounts.title', '用户账号')}><ProTable<PlayerAccount> rowKey="account_id" columns={columns} request={async (params) => { const result = await listAccounts(params); return { data: result.data, total: result.total, success: true }; }} toolBarRender={() => [<Button key="register" type="primary" icon={<UserAddOutlined />} onClick={() => { registerForm.resetFields(); setRegisterOpen(true); }}>{t('players.account.register', '注册账号')}</Button>]} /><Drawer title={t('common.detail', '详情')} open={!!drawer} onClose={() => setDrawer(undefined)} size="large">{drawer && <Descriptions column={1} items={Object.entries(drawer).map(([label, children]) => ({ key: label, label: labels[label] ?? label, children }))} />}</Drawer><Modal title={t('players.account.resetPassword', '重置密码')} open={!!passwordId} onCancel={() => setPasswordId(undefined)} onOk={() => form.submit()}><Form form={form} onFinish={async ({ password }) => { if (!passwordId) return; await resetPassword(passwordId, password); message.success(t('players.account.passwordReset', '密码已重置')); setPasswordId(undefined); }}><Form.Item name="password" label={t('players.account.newPassword', '新密码')} rules={[{ required: true, min: 8 }]}><Input.Password /></Form.Item></Form></Modal><Modal title={t('players.account.register', '注册账号')} open={registerOpen} onCancel={() => setRegisterOpen(false)} onOk={() => registerForm.submit()}><Form form={registerForm} onFinish={async (values) => { await registerAccount(values); message.success(t('players.account.registered', '账号已注册')); setRegisterOpen(false); }}><Form.Item name="userid" label={t('players.account.username', '用户名')} rules={[{ required: true, min: 4, max: 23 }]}><Input /></Form.Item><Form.Item name="user_pass" label={t('players.account.newPassword', '新密码')} rules={[{ required: true, min: 8 }]}><Input.Password /></Form.Item><Form.Item name="email" label={t('players.account.email', '邮箱')} rules={[{ required: true, type: 'email' }]}><Input /></Form.Item><Form.Item name="sex" label={t('players.account.sex', '性别')} initialValue="M"><Input /></Form.Item></Form></Modal></PageContainer>;
}
